# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2023-04-05 20:02:16
"""
import arcpy

def Geog592():  # Geog592

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    PM25_2_ = "PM25"
    Ethiopia_2_ = "Ethiopia"

    # Process: Copy Raster (Copy Raster) (management)
    PM2_5Raster_crf = "D:\\OneDrive\\Desktop\\GEOG592\\PM2.5Raster.crf"
    arcpy.management.CopyRaster(in_raster=PM25_2_, out_rasterdataset=PM2_5Raster_crf, config_keyword="", background_value=None, nodata_value="3.4e+38", onebit_to_eightbit="NONE", colormap_to_RGB="NONE", pixel_type="", scale_pixel_value="NONE", RGB_to_Colormap="NONE", format="CRF", transform="NONE", process_as_multidimensional="ALL_SLICES", build_multidimensional_transpose="NO_TRANSPOSE")

    # Process: Create Space Time Cube From Multidimensional Raster Layer (Create Space Time Cube From Multidimensional Raster Layer) (stpm)
    PM2_5mrl_nc = "D:\\OneDrive\\Desktop\\GEOG592\\PM2.5mrl.nc"
    arcpy.stpm.CreateSpaceTimeCubeMDRasterLayer(in_md_raster=PM2_5Raster_crf, output_cube=PM2_5mrl_nc, fill_empty_bins="ZEROS")

    # Process: Emerging Hot Spot Analysis (Emerging Hot Spot Analysis) (stpm)
    PM2_EmergingHotSpotAnalysis = "D:\\OneDrive\\Documents\\ArcGIS\\Packages\\InvestigatePollutionPatterns_026795\\p20\\investigateglobalpollutionpatterns.gdb\\PM2_EmergingHotSpotAnalysis"
    arcpy.stpm.EmergingHotSpotAnalysis(in_cube=PM2_5mrl_nc, analysis_variable="PM_2_5_NONE_ZEROS", output_features=PM2_EmergingHotSpotAnalysis, neighborhood_distance="", neighborhood_time_step=1, polygon_mask="", conceptualization_of_spatial_relationships="K_NEAREST_NEIGHBORS", number_of_neighbors=8, define_global_window="INDIVIDUAL_TIME_STEP")

    # Process: Visualize Space Time Cube in 2D (Visualize Space Time Cube in 2D) (stpm)
    PM25_2D = "D:\\OneDrive\\Documents\\ArcGIS\\Packages\\InvestigatePollutionPatterns_026795\\p20\\investigateglobalpollutionpatterns.gdb\\PM25_2D"
    arcpy.stpm.VisualizeSpaceTimeCube2D(in_cube=PM2_5mrl_nc, cube_variable="PM_2_5_NONE_ZEROS", display_theme="TRENDS", output_features=PM25_2D, enable_time_series_popups="NO_POPUP")

    # Process: Visualize Space Time Cube in 3D (Visualize Space Time Cube in 3D) (stpm)
    PM25_3D = "D:\\OneDrive\\Documents\\ArcGIS\\Packages\\InvestigatePollutionPatterns_026795\\p20\\investigateglobalpollutionpatterns.gdb\\PM25_3D"
    arcpy.stpm.VisualizeSpaceTimeCube3D(in_cube=PM2_5mrl_nc, cube_variable="PM_2_5_NONE_ZEROS", display_theme="VALUE", output_features=PM25_3D)

    # Process: Clip (Clip) (analysis)
    PM25_3D_Clip = "D:\\OneDrive\\Documents\\ArcGIS\\Packages\\InvestigatePollutionPatterns_026795\\p20\\investigateglobalpollutionpatterns.gdb\\PM25_3D_Clip"
    arcpy.analysis.Clip(in_features=PM25_3D, clip_features=Ethiopia_2_, out_feature_class=PM25_3D_Clip, cluster_tolerance="")

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"D:\OneDrive\Documents\ArcGIS\Packages\InvestigatePollutionPatterns_026795\p20\investigateglobalpollutionpatterns.gdb", workspace=r"D:\OneDrive\Documents\ArcGIS\Packages\InvestigatePollutionPatterns_026795\p20\investigateglobalpollutionpatterns.gdb"):
        Geog592()
