# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2022-09-14 14:27:27
"""
import arcpy


# To allow overwriting outputs change overwriteOutput option to True.
arcpy.env.overwriteOutput = True

CITIES_SHP = "T:\\Data\\Lab3\\CITIES.SHP"
intrstat_shp = "T:\\Data\\Lab3\\intrstat.shp"

#User input section
#Get users' input for choices of highways and buffer distance value
hwys = input("Please type the highways you want to analyze - ex: I40 I80 I90\n")
bufDist = input("ALso tell me the buffer distance value here. Ex: 30\n")

hwyList = hwys.split() #expect to receive a list of strings - ["I40","I80","I90"]
for aHwy in hwyList:
    # Process: Select (Select) (analysis)
    hwysel_shp = "T:\\Admin\\Lab3\\hwysel.shp"
    hwySql = "ROUTE_NUM = '" + aHwy +"'"
    arcpy.analysis.Select(intrstat_shp, hwysel_shp, hwySql)

    # Process: Buffer (Buffer) (analysis)
    hwyselbuf_shp = "T:\\Admin\\Lab3\\hwyselbuf.shp"
    bufExp =bufDist  +" Miles"
    arcpy.analysis.Buffer(hwysel_shp, hwyselbuf_shp, bufExp)
    print(aHwy+ " Buffer is created.")
    
    # Process: Clip (Clip) (analysis)
    hwyselbufSelCities = "T:\\Admin\\Lab3\\"+aHwy+bufDist+"SelCities.shp"
    arcpy.analysis.Clip(in_features=CITIES_SHP, clip_features=hwyselbuf_shp, out_feature_class=hwyselbufSelCities, cluster_tolerance="")

    # Process: Summary Statistics (2) (Summary Statistics) (analysis)
    sumTable_dbf = "T:\\Admin\\Lab3\\"+aHwy+bufDist+"sumTable.dbf"
    arcpy.analysis.Statistics(in_table=hwyselbufSelCities, out_table=sumTable_dbf, statistics_fields=[["HISPANIC", "SUM"]], case_field=[], concatenation_separator="")
    print(aHwy+ " has been completed")

print("All completed")
