# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2023-03-07 11:38:35
"""
import arcpy

def Model():  # Model

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    cities_2_ = "cities"
    LAKES = "LAKES"

    # Process: Buffer (Buffer) (analysis)
    LakesBuf25 = "C:\\Users\\Chima Okoli\\OneDrive\\Desktop\\GEOG592\\Midterm\\MyProject.gdb\\LakesBuf25"
    arcpy.analysis.Buffer(in_features=LAKES, out_feature_class=LakesBuf25, buffer_distance_or_field="25 NauticalMiles", line_side="FULL", line_end_type="ROUND", dissolve_option="NONE", dissolve_field=[], method="PLANAR")

    # Process: Select Layer By Location (Select Layer By Location) (management)
    cities, CitiesInLkBUf25, Count = arcpy.management.SelectLayerByLocation(in_layer=[cities_2_], overlap_type="WITHIN", select_features=LakesBuf25, search_distance="", selection_type="NEW_SELECTION", invert_spatial_relationship="NOT_INVERT")

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"C:\Users\Chima Okoli\OneDrive\Desktop\GEOG592\Midterm\MyProject.gdb", workspace=r"C:\Users\Chima Okoli\OneDrive\Desktop\GEOG592\Midterm\MyProject.gdb"):
        Model()
